-- MySQL Script generated by MySQL Workbench
-- jue 17 sep 2015 02:40:04 PET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `username` (16) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `score` INT NULL,
  `steamid` VARCHAR(45) NULL,
  `facebookid` VARCHAR(45) NULL,
  `profile_info` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`));


-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`article` ;

CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `idarticle` INT NOT NULL,
  `score` INT NULL,
  `text` TEXT NULL,
  `numviews` INT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idarticle`),
  INDEX `fk_article_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_article_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `idcomment` INT NOT NULL,
  `TEXT` TEXT NULL,
  `score` INT NULL,
  `article_idarticle` INT NOT NULL,
  `user_iduser` INT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comment_article1_idx` (`article_idarticle` ASC),
  INDEX `fk_comment_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_comment_article1`
    FOREIGN KEY (`article_idarticle`)
    REFERENCES `mydb`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `idcategory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topic_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`topic_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`topic_category` (
  `idtopic_category` INT NOT NULL,
  `articleid` INT NULL,
  PRIMARY KEY (`idtopic_category`),
  INDEX `fk_article_idx` (`articleid` ASC),
  CONSTRAINT `fk_topic_join`
    FOREIGN KEY ()
    REFERENCES `mydb`.`category` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article`
    FOREIGN KEY (`articleid`)
    REFERENCES `mydb`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time`  NULL,
  `article_idarticle` INT NOT NULL,
  INDEX `fk_timestamps_article1_idx` (`article_idarticle` ASC),
  CONSTRAINT `fk_timestamps_article1`
    FOREIGN KEY (`article_idarticle`)
    REFERENCES `mydb`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`comment_has_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment_has_comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment_has_comment` (
  `comment_idcomment` INT NOT NULL,
  `comment_idcomment1` INT NOT NULL,
  PRIMARY KEY (`comment_idcomment`, `comment_idcomment1`),
  INDEX `fk_comment_has_comment_comment2_idx` (`comment_idcomment1` ASC),
  INDEX `fk_comment_has_comment_comment1_idx` (`comment_idcomment` ASC),
  CONSTRAINT `fk_comment_has_comment_comment1`
    FOREIGN KEY (`comment_idcomment`)
    REFERENCES `mydb`.`comment` (`idcomment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_has_comment_comment2`
    FOREIGN KEY (`comment_idcomment1`)
    REFERENCES `mydb`.`comment` (`idcomment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
